name: Run Postman Collection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman + HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run application.json \
          --reporters cli,htmlextra,json \
          --reporter-htmlextra-export results.html \
          --reporter-json-export results.json \
          --reporter-htmlextra-title "CI/CD Test Report" \
          --reporter-htmlextra-titleSize 4 \
          --reporter-htmlextra-showEnvironmentData

      - name: Upload TMS Collection HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: |
            results.html
            results.json
      - name: Extract summary counts
        run: |
          total=$(jq '.run.stats.tests.total' results.json)
          failed=$(jq '.run.stats.tests.failed' results.json)
          skipped=$(jq '.run.stats.tests.pending' results.json)
          passed=$((total - failed - skipped))

          echo "TOTAL=$total" >> $GITHUB_ENV
          echo "PASSED=$passed" >> $GITHUB_ENV
          echo "FAILED=$failed" >> $GITHUB_ENV
          echo "SKIPPED=$skipped" >> $GITHUB_ENV

      - name: Generate simple HTML summary
        run: |
          cat <<EOF > summary.html
          <html>
          <head>
            <style>
              body { font-family: Arial; display: flex; gap: 20px; }
              .box { padding: 20px; border-radius: 10px; color: white; font-size: 20px; font-weight: bold; text-align: center; }
              .total { background: #444; }
              .passed { background: green; }
              .failed { background: red; }
              .skipped { background: orange; }
            </style>
          </head>
          <body>
            <div class="box total">Total<br>${{ env.TOTAL }}</div>
            <div class="box passed">Passed<br>${{ env.PASSED }}</div>
            <div class="box failed">Failed<br>${{ env.FAILED }}</div>
            <div class="box skipped">Skipped<br>${{ env.SKIPPED }}</div>
          </body>
          </html>
          EOF

      - name: Call REST API with summary + HTML report
        run: |
          curl --location 'https://d3f4c03b6b08.ngrok-free.app/api/v1/api-test-runner/get-files' \
            --header 'ngrok-skip-browser-warning: 69420' \
            --header 'Referer: http://localhost:5173/' \
            --header 'User-Agent: GitHubActionsBot/1.0' \
            --header 'Accept: application/json, text/plain, */*' \
            -F "attachments=@summary.html;type=text/html" \
            -F "total=${{ env.TOTAL }}" \
            -F "pass=${{ env.PASSED }}" \
            -F "failed=${{ env.FAILED }}" \
            -F "skip=${{ env.SKIPPED }}"

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.PASSWORD }}
          subject: "Postman Test Report"
          to: ${{ secrets.TO }}
          from: ${{ secrets.FROM }}
          body: "Attached is the Postman test run report."
          attachments: results.html
