name: Run Postman Collection

on:
  push:
    branches: [ main ]   # Run on every push to main
  pull_request:          # Or when PR is raised
    branches: [ main ]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run application.json \
            --reporters cli,junit \
            --reporter-junit-export results.xml
